- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ items }}"
    state: present 
    loop:
      - libssl-dev 
      - zlib1g-dev 
      - libbz2-dev 
      - libreadline-dev 
      - libsqlite3-dev 
      - llvm 
      - libncursesw5-dev 
      - xz-utils 
      - tk-dev 
      - libxml2-dev 
      - libxmlsec1-dev 
      - libffi-dev 
      - liblzma-dev
     
- name: Remove existing Pyenv directory if present
  ansible.builtin.file:
    path: /root/.pyenv
    state: absent    

- name: Download pyenv installation script
  ansible.builtin.get_url:
    url: "https://pyenv.run"
    dest: "/root/pyenv_install.sh"
    mode: "055"

- name: Execute installation file 
  ansible.builtin.command: /root/pyenv_install.sh

- name: Setup environment files 
  ansible.builtin.lineinfile:
    path: "{{ ansible_home }}/.bashrc"
    line: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)" 
  
- name: Execute "$SHELL" command
  ansible.builtin.shell:
    cmd: "exec \"$SHELL\""

- name: install python version
  args:
    executable: /bin/bash
  ansible.builtin.shell:
    cmd: "pyenv install {{ local_version }}"
    creates: "{{ ansible_env.HOME }}/.pyenv/versions:3.7.2"
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"

- name: Copy a project to private EC2
  ansible.builtin.copy:
    src: "/home/sujata/simple-django-project"
    dest: "/home/ubuntu/app"
    
- name: Set local pyenv
  args:
    executable: /bin/bash
    chdir: "/home/ubuntu/app"
  ansible.builtin.shell: 
    cmd: "pyenv local {{ local_version }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"  


- name: Create Virtual environment
  command:
    cmd: python3 -m venv {{ project_path }}/project_venv
    creates: "{{ project_path }}/project_venv"

- name: Install specified requirements for project
  ansible.builtin.pip:
    requirements: /home/ubuntu/app/requirements.txt
    virtualenv: 


