- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create Database
  mysql_db:
    name: mydatabase
    state: present 

- name: Create database user with name 'sujata' and password with all database privileges
  community.mysql.mysql_user:
    name: sujata
    password: password
    priv: '*.*:ALL'
    state: present




