- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Start MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true

- name: Create database user with name 'suj' and password with all database privileges
  community.mysql.mysql_user:
    name: suj
    password: password
    priv: '*.*:ALL'
    state: present



