- name: Copy a project to private EC2
  ansible.builtin.copy:
    src: "/home/sujata/simple-django-project-main/"
    dest: "{{ app_path }}"

- name: Set local pyenv
  args:
    executable: /bin/bash
    chdir: "{{ app_path }}"
  ansible.builtin.command: 
    cmd: "pyenv local {{ local_version }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"     

- name: Install virtualenv
  ansible.builtin.pip:
    name: virtualenv
    executable: pip3

- name: Set python virual env
  command:
    cmd: "virtualenv {{ app_path }} -p python3"

- name: Create virtual environment
  command: virtualenv "{{ app_path }}"/env
  args:
    creates: /home/ubuntu/app/env

- name: Activate virtual environment
  shell: source "{{ app_path }}"/env/bin/activate 
  args:
    executable: /bin/bash   
 
- name: Install specified requirements for project
  ansible.builtin.pip:
    requirements: /home/ubuntu/app/requirements.txt
    virtualenv: /home/ubuntu/app/env

- name: Configure Django settings
  ansible.builtin.template:
    src: templates/settings.py.j2
    dest: /home/ubuntu/app/panorbit/settings.py

- name: Make migrations
  ansible.builtin.command: python /home/ubuntu/app/manage.py makemigrations

- name: Migrate database  
  ansible.builtin.command: python /home/ubuntu/app/manage.py migrate

- name: Rebuild search index
  ansible.builtin.command: python /home/ubuntu/app/manage.py rebuild_index

- name: Run Django server
  ansible.builtin.command: python /home/ubuntu/app/manage.py runserver 0:8001    