- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true  
    

- name: Copy configuration file 
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
   