---
- hosts: nginx
  become: true
  gather_facts: true
  roles:
   - nginx
   - reverse_proxy
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_bucket_name: sujata-backend
    
- hosts: python
  become: true
  gather_facts: true
  roles:
  - nginx
  - pyenv
  - mysql
  - django
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_bucket_name: sujata-backend
    ansible_aws_ssm_timeout: 3000
    ansible_python_interpreter: /usr/bin/python3


